// MARK: - Text Injection & Clipboard Engine

struct TextInjector {
    // Marker types so clipboard managers (Paste, Maccy, Raycast Clipboard History, ...) skip
    // archiving ephemeral dictation text - org.nspasteboard.org convention.
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    private static let mutationLock = NSLock()
    private static let restorationLock = NSLock()
    private static var pendingRestoration: (version: Int, contents: [NSPasteboardItem])?
    private static let preparation = ClipboardPreparation<[NSPasteboardItem]>(
        version: { NSPasteboard.general.changeCount },
        read: { snapshotClipboard() }
    )

    static func prepareClipboard() { preparation.prepare() }
    static func discardPreparedClipboard() { preparation.discard() }
    static func awaitPreparedClipboard(timeout: Double = 0.15, completion: @escaping (Bool) -> Void) {
        preparation.awaitPrepared(timeout: timeout, completion: completion)
    }

    private static func snapshotClipboard() -> [NSPasteboardItem]? {
        let pb = NSPasteboard.general
        let count = pb.changeCount
        restorationLock.lock()
        let pending = pendingRestoration
        restorationLock.unlock()
        // Consecutive turns must preserve the user's original clipboard, not our temporary text.
        if let pending = pending, pending.version == count { return pending.contents }
        guard let items = pb.pasteboardItems else { return [] }
        var copiedItems: [NSPasteboardItem] = []
        for item in items {
            let newItem = NSPasteboardItem()
            for type in item.types {
                guard let data = item.data(forType: type), newItem.setData(data, forType: type) else {
                    return nil
                }
            }
            copiedItems.append(newItem)
        }
        return copiedItems
    }

    private static func restoreClipboard(_ savedItems: [NSPasteboardItem]) {
        let pb = NSPasteboard.general
        pb.clearContents()
        if !savedItems.isEmpty {
            pb.writeObjects(savedItems)
        }
    }

    enum Outcome { case dispatched, clipboardUnavailable, dispatchCancelled, failed }
    struct InjectionResult {
        let outcome: Outcome
        let latencyMs: Double
    }

    static func inject(
        text: String, restorePreviousClipboard: Bool = true, completionSound: Bool = true,
        appendSpace: Bool = false, shouldDispatch: () -> Bool = { true }
    ) -> InjectionResult {
        let start = ProcessInfo.processInfo.systemUptime
        func result(_ outcome: Outcome) -> InjectionResult {
            InjectionResult(outcome: outcome, latencyMs: (ProcessInfo.processInfo.systemUptime - start) * 1000)
        }
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return result(.failed) }
        let payload = appendSpace ? trimmed + " " : trimmed
        let source = CGEventSource(stateID: .hidSystemState)
        guard let keyDown = CGEvent(keyboardEventSource: source, virtualKey: 0x09, keyDown: true),
            let keyUp = CGEvent(keyboardEventSource: source, virtualKey: 0x09, keyDown: false)
        else {
            return result(.failed)
        }
        keyDown.flags = .maskCommand
        keyUp.flags = .maskCommand
        let item = NSPasteboardItem()
        guard item.setString(payload, forType: .string),
            item.setData(Data(), forType: transientType),
            item.setData(Data(), forType: autoGeneratedType)
        else { return result(.failed) }
        let previous = restorePreviousClipboard ? preparation.take() : nil
        guard !restorePreviousClipboard || previous != nil else { return result(.clipboardUnavailable) }
        let pb = NSPasteboard.general
        // Recheck after the caller's focus check: it may need a main-thread hop.
        guard shouldDispatch() else { return result(.dispatchCancelled) }
        mutationLock.lock()
        if let previous = previous, pb.changeCount != previous.version {
            mutationLock.unlock()
            return result(.clipboardUnavailable)
        }
        pb.clearContents()
        let clearedCount = pb.changeCount
        guard pb.writeObjects([item]) else {
            if let previous = previous, pb.changeCount == clearedCount { restoreClipboard(previous.contents) }
            mutationLock.unlock()
            return result(.failed)
        }
        let ourChangeCount = pb.changeCount
        // This reports event dispatch, not confirmation that the destination consumed the text.
        keyDown.post(tap: .cghidEventTap)
        usleep(10_000)
        keyUp.post(tap: .cghidEventTap)
        if let previous = previous {
            restorationLock.lock()
            pendingRestoration = (ourChangeCount, previous.contents)
            restorationLock.unlock()
            DispatchQueue.global().asyncAfter(deadline: .now() + 1) {
                mutationLock.lock()
                if NSPasteboard.general.changeCount == ourChangeCount { restoreClipboard(previous.contents) }
                mutationLock.unlock()
                restorationLock.lock()
                if pendingRestoration?.version == ourChangeCount { pendingRestoration = nil }
                restorationLock.unlock()
            }
        }
        mutationLock.unlock()
        if completionSound { SoundManager.playCommitSound() }
        return result(.dispatched)
    }

    /// Puts text on the clipboard WITHOUT synthesizing ⌘V or restoring the previous clipboard -
    /// the copy-only fallback for secure-input and mid-turn focus changes, so the text stays put
    /// for the user to paste manually.
    static func copyOnly(text: String, appendSpace: Bool = false) -> Bool {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return false }
        let payload = appendSpace ? trimmed + " " : trimmed
        let item = NSPasteboardItem()
        guard item.setString(payload, forType: .string),
            item.setData(Data(), forType: transientType),
            item.setData(Data(), forType: autoGeneratedType)
        else { return false }
        let pasteboard = NSPasteboard.general
        mutationLock.lock()
        defer { mutationLock.unlock() }
        pasteboard.clearContents()
        return pasteboard.writeObjects([item])
    }
}

// A provider can block inside AppKit. Keep at most one reader and one latest request;
// callers wait through a timer, never on the provider's worker.
final class ClipboardPreparation<Contents> {
    struct Snapshot { let version: Int; let contents: Contents }
    private let lock = NSLock()
    private let queue = DispatchQueue(label: "com.justspeak.clipboard", qos: .utility)
    private let version: () -> Int
    private let read: () -> Contents?
    private var generation: UInt64 = 0
    private var requested = false
    private var running = false
    private var reading = false
    private var readingGeneration: UInt64 = 0
    private var prepared: Snapshot?
    private var waiters: [UUID: (Bool) -> Void] = [:]

    init(version: @escaping () -> Int, read: @escaping () -> Contents?) {
        self.version = version
        self.read = read
    }

    func prepare() {
        lock.lock()
        generation &+= 1
        prepared = nil
        requested = true
        let start = !running
        running = true
        lock.unlock()
        if start { queue.async { self.run() } }
    }

    func discard() {
        lock.lock()
        generation &+= 1
        requested = false
        prepared = nil
        let callbacks = Array(waiters.values)
        waiters.removeAll()
        lock.unlock()
        callbacks.forEach { $0(false) }
    }

    func take() -> Snapshot? {
        let currentVersion = version()
        lock.lock()
        let snapshot = prepared
        prepared = nil
        generation &+= 1
        requested = false
        lock.unlock()
        return snapshot?.version == currentVersion ? snapshot : nil
    }

    func awaitPrepared(timeout: Double, completion: @escaping (Bool) -> Void) {
        let currentVersion = version()
        let id = UUID()
        lock.lock()
        let ready = prepared?.version == currentVersion
        if !ready { waiters[id] = completion }
        let start = !ready && !running
        if !ready && (!reading || readingGeneration != generation) && !requested {
            generation &+= 1
            prepared = nil
            requested = true
        }
        if start { running = true }
        lock.unlock()
        if ready { completion(true); return }
        if start { queue.async { self.run() } }
        DispatchQueue.global().asyncAfter(deadline: .now() + max(0, timeout)) {
            self.lock.lock()
            let callback = self.waiters.removeValue(forKey: id)
            self.lock.unlock()
            callback?(false)
        }
    }

    private func run() {
        while true {
            lock.lock()
            guard requested else { running = false; lock.unlock(); return }
            requested = false
            reading = true
            let token = generation
            readingGeneration = token
            lock.unlock()
            let before = version()
            let contents = read()
            let after = version()
            lock.lock()
            reading = false
            let current = token == generation
            if current, before == after, let contents = contents {
                prepared = Snapshot(version: before, contents: contents)
            }
            // Retry a concurrent user copy only while a bounded waiter still needs a snapshot.
            let retry = current && before != after && !waiters.isEmpty
            if retry { requested = true }
            let callbacks = current && !retry ? Array(waiters.values) : []
            if current && !retry { waiters.removeAll() }
            let ready = prepared != nil
            lock.unlock()
            callbacks.forEach { $0(ready) }
        }
    }
}
