// MARK: - Text Injection & Clipboard Engine

struct TextInjector {
    // Marker types so clipboard managers (Paste, Maccy, Raycast Clipboard History, ...) skip
    // archiving ephemeral dictation text - org.nspasteboard.org convention.
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    private struct Snapshot {
        let changeCount: Int
        let items: [NSPasteboardItem]
    }
    private static let preparationQueue = DispatchQueue(label: "com.justspeak.clipboard", qos: .utility)
    private static let preparationLock = NSLock()
    private static var generation: UInt64 = 0
    private static var prepared: Snapshot?

    static func prepareClipboard() {
        preparationLock.lock()
        generation &+= 1
        let token = generation
        prepared = nil
        preparationLock.unlock()
        preparationQueue.async {
            preparationLock.lock()
            let current = token == generation
            preparationLock.unlock()
            guard current else { return }
            let count = NSPasteboard.general.changeCount
            let items = snapshotClipboard()
            guard NSPasteboard.general.changeCount == count else { return }
            preparationLock.lock()
            if token == generation { prepared = Snapshot(changeCount: count, items: items) }
            preparationLock.unlock()
        }
    }

    static func discardPreparedClipboard() {
        preparationLock.lock()
        generation &+= 1
        prepared = nil
        preparationLock.unlock()
    }

    private static func takeClipboardSnapshot() -> [NSPasteboardItem] {
        preparationLock.lock()
        let snapshot = prepared
        prepared = nil
        generation &+= 1
        preparationLock.unlock()
        if let snapshot = snapshot, snapshot.changeCount == NSPasteboard.general.changeCount {
            return snapshot.items
        }
        // An unfinished or stale preparation must not overwrite a newer user copy.
        return snapshotClipboard()
    }

    private static func snapshotClipboard() -> [NSPasteboardItem] {
        let pb = NSPasteboard.general
        guard let items = pb.pasteboardItems else { return [] }
        var copiedItems: [NSPasteboardItem] = []
        for item in items {
            let newItem = NSPasteboardItem()
            for type in item.types {
                if let data = item.data(forType: type) {
                    newItem.setData(data, forType: type)
                }
            }
            copiedItems.append(newItem)
        }
        return copiedItems
    }

    private static func restoreClipboard(_ savedItems: [NSPasteboardItem]) {
        let pb = NSPasteboard.general
        pb.clearContents()
        if !savedItems.isEmpty {
            pb.writeObjects(savedItems)
        }
    }

    static func inject(text: String, restorePreviousClipboard: Bool = true, completionSound: Bool = true, appendSpace: Bool = false) -> (success: Bool, latencyMs: Double) {
        let startTime = ProcessInfo.processInfo.systemUptime
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else {
            Logger.warn("INJECT", "Refusing to inject empty string.")
            return (false, 0)
        }
        // Appended after the trim, or the trim would eat it: one trailing space so the next
        // dictation doesn't fuse onto this one.
        let payload = appendSpace ? trimmed + " " : trimmed

        // 1. Snapshot previous clipboard to preserve user data. The snapshot materializes
        // every representation of every pasteboard item synchronously on the paste path, so
        // surface it when it's actually slow (large images/files on the clipboard).
        let snapshotStart = ProcessInfo.processInfo.systemUptime
        let previousClipboard = restorePreviousClipboard ? takeClipboardSnapshot() : []
        let snapshotMs = (ProcessInfo.processInfo.systemUptime - snapshotStart) * 1000.0
        if snapshotMs > 5.0 {
            Logger.debug("INJECT", "Clipboard snapshot took \(String(format: "%.0f", snapshotMs))ms (\(previousClipboard.count) items)")
        }

        // 2. Put text onto pasteboard for active app injection. Written as an NSPasteboardItem
        // with transient/auto-generated marker types so clipboard managers skip archiving it.
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(payload, forType: .string)
        item.setData(Data(), forType: transientType)
        item.setData(Data(), forType: autoGeneratedType)
        let pbSuccess = pasteboard.writeObjects([item])
        guard pbSuccess else {
            Logger.error("INJECT", "Failed to write text to NSPasteboard.")
            return (false, 0)
        }
        let ourChangeCount = pasteboard.changeCount

        // 3. Synthesize Cmd+V via CGEvent (posted exclusively to cghidEventTap)
        let source = CGEventSource(stateID: .hidSystemState)
        let vKeyCode: CGKeyCode = 0x09  // Virtual keycode for 'v'

        var eventSuccess = false
        if let keyDown = CGEvent(keyboardEventSource: source, virtualKey: vKeyCode, keyDown: true),
            let keyUp = CGEvent(keyboardEventSource: source, virtualKey: vKeyCode, keyDown: false)
        {

            keyDown.flags = .maskCommand
            keyUp.flags = .maskCommand

            keyDown.post(tap: .cghidEventTap)
            usleep(10_000)  // 10ms key press hold - sufficient for a synthesized Cmd+V to register
            keyUp.post(tap: .cghidEventTap)

            eventSuccess = true
        }

        // 4. Fallback to AppleScript only if CGEvent dispatch failed
        if !eventSuccess {
            Logger.warn("INJECT", "CGEvent posting failed; executing AppleScript System Events fallback...")
            let appleScript = NSAppleScript(source: "tell application \"System Events\" to keystroke \"v\" using command down")
            var errorInfo: NSDictionary?
            appleScript?.executeAndReturnError(&errorInfo)
            if let error = errorInfo {
                Logger.error("INJECT", "AppleScript fallback error: \(error)")
            } else {
                eventSuccess = true
            }
        }

        // 5. Asynchronously restore user's previous clipboard after ~1s (giving slow/Electron
        // apps like Slack/VSCode time to consume it), but only if nothing else has touched the
        // pasteboard since our write - otherwise a user copy (or another app) would get clobbered.
        if restorePreviousClipboard && !previousClipboard.isEmpty {
            DispatchQueue.global().asyncAfter(deadline: .now() + 1.0) {
                guard NSPasteboard.general.changeCount == ourChangeCount else { return }
                restoreClipboard(previousClipboard)
            }
        }

        if completionSound {
            SoundManager.playCommitSound()
        }

        let elapsed = (ProcessInfo.processInfo.systemUptime - startTime) * 1000.0
        return (eventSuccess, elapsed)
    }

    /// Puts text on the clipboard WITHOUT synthesizing ⌘V or restoring the previous clipboard -
    /// the copy-only fallback for secure-input and mid-turn focus changes, so the text stays put
    /// for the user to paste manually.
    static func copyOnly(text: String, appendSpace: Bool = false) -> Bool {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return false }
        let payload = appendSpace ? trimmed + " " : trimmed
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(payload, forType: .string)
        item.setData(Data(), forType: transientType)
        item.setData(Data(), forType: autoGeneratedType)
        return pasteboard.writeObjects([item])
    }
}
